#!/bin/bash


## BUILDER DIRECTORY
BASEDIR="`dirname "$0"`"
# echo -e "BASEDIR: $BASEDIR"


## COLORS
GREEN='\033[1;32m' # Green
BLUE='\033[1;34m' # Blue
RED='\033[1;31m' # Red
RESET='\033[0m' # No Color
# echo -e "${RED}Green${RESET} - ${BLUE}Blue${RESET} - ${RED}Red${RESET}"


## FIND CURRENT OS
OS="Unknown"
ENVIRONMENT=staging
if [[ "$OSTYPE" == "linux-gnu" ]];then
	OS="Linux"
	ENVIRONMENT=remote
elif [[ "$OSTYPE" == "darwin"* ]];then
	OS="MacOS"
	ENVIRONMENT=local
elif [[ "$OSTYPE" == "cygwin" ]];then
	# POSIX compatibility layer and Linux environment emulation for Windows
	OS="cygwin"
	ENVIRONMENT=remote
elif [[ "$OSTYPE" == "msys" ]];then
	# Lightweight shell and GNU utilities compiled for Windows (part of MinGW)
	OS="msys"
	ENVIRONMENT=local
elif [[ "$OSTYPE" == "win32" ]];then
	OS="Win32"
	ENVIRONMENT=local
elif [[ "$OSTYPE" == "freebsd"* ]];then
	OS="FreeBSD"
	ENVIRONMENT=remote
fi
#echo "Operating System: ${OS}"


## ENVIRONMENT VARIABLES
ENV_FILE="$BASEDIR/.env"

# If environment file doesn't exist, try using sample file
if [[ ! -f $ENV_FILE ]];then

	# If sample environment file also doesn't exist, exit
	if [[ -f "${ENV_FILE}.${ENVIRONMENT}" ]];then

		# Copy from the sample
		cp "${ENV_FILE}.${ENVIRONMENT}" "$ENV_FILE"

	fi

fi

# Include it
source $ENV_FILE


# CHECK DOCKER WHETHER OR NOT RUNNING
rep=$(docker ps -q &>/dev/null)
status=$?
if [[ "$status" != "0" ]];then

	echo -e "${BLUE}Docker engine is not running. Please open the docker and wait until it starts.${RESET}"
	exit 1

fi




## CLONNING THE SERVICES
# Landing Page Repo
if [[ ! -d landing ]]; then

	echo "Landing clonning..."
	git clone https://github.com/Revisionary/revisionary-landing.git landing

fi

# Dashboard Page Repo
if [[ ! -d dashboard ]]; then

	echo "Dashboard clonning..."
	git clone https://github.com/Revisionary/revisionary-dashboard.git dashboard

fi

# Backend Repo
if [[ ! -d backend ]]; then

	echo "Backend clonning..."
	git clone https://github.com/Revisionary/revisionary-backend-nginx.git backend

fi

# Backend Sources Repo
if [[ ! -d backend/src ]]; then

	echo "Backend sources clonning..."
	git clone https://github.com/Revisionary/revisionary-backend-src.git backend/src

fi

# Database Repo
if [[ ! -d database ]]; then

	echo "Database clonning..."
	git clone https://github.com/Revisionary/revisionary-database.git database

fi

# Chrome Repo
if [[ ! -d chrome ]]; then

	echo "Chrome clonning..."
	git clone https://github.com/Revisionary/revisionary-chrome.git chrome

fi




## FUNCTIONS
# Docker Compose bundle
function docker_compose {
	docker-compose --env-file ".env" -f "docker-compose-${ENV_NAME}.yml" "$@"
}


# ACTIONS
ACTION=$1
echo -e "Started action: ${BLUE}$ACTION${RESET} ($ENV_NAME)"
if [[ $ACTION == install ]]; then


	echo "Building the project..."
	docker_compose up -d --build
	echo "Project built."


	echo "Updating file permissions in server..."
	docker_compose exec backend chown -R www-data:www-data /backend
	docker_compose exec backend find /backend -type f -exec chmod 644 {} \;
	docker_compose exec backend find /backend -type d -exec chmod 755 {} \;
	echo "File permissions updated in server"


	# echo "Checking MySQL to be ready..."
	# while ! docker_compose exec database mysqladmin --user=${DB_USER} --password=${DB_ROOT_PASSWORD} --host "${LOCAL_IP}" ping --silent &> /dev/null ; do
	# 	echo "Waiting for database connection..."
	# 	sleep 3
	# done
	# echo "Site is ready!"


elif [[ $ACTION == pull ]]; then


	echo "Main Project:"
	git pull

	echo "Landing:"
	( cd landing && git pull )

	echo "Dashboard:"
	( cd dashboard && git pull )

	echo "Backend:"
	( cd backend && git pull )

	echo "Backend Source:"
	( cd backend/src && git pull )

	echo "Database:"
	( cd database && git pull )

	echo "Chrome:"
	( cd chrome && git pull )


elif [[ $ACTION == recreate ]]; then


	echo "Recreating the containers..."
	docker_compose up -d --force-recreate
	echo "Containers recreated."


	# echo "Updating file permissions in server..."
	# docker_compose exec backend chown -R www-data:www-data /backend
	# docker_compose exec backend find /backend -type f -exec chmod 644 {} \;
	# docker_compose exec backend find /backend -type d -exec chmod 755 {} \;
	# echo "File permissions updated in server"


	# echo "Checking MySQL to be ready..."
	# while ! docker_compose exec database mysqladmin --user=${DB_USER} --password=${DB_ROOT_PASSWORD} --host "${LOCAL_IP}" ping --silent &> /dev/null ; do
	# 	echo "Waiting for database connection..."
	# 	sleep 3
	# done
	# echo "Site is ready!"


elif [[ $ACTION == rebuild ]]; then


	# Predefined project to build
	echo "Rebuilding the project..."
	if [[ ! -z $2 ]]; then

		docker_compose up --no-deps -d --build --force-recreate $2

	else


		docker_compose up -d --build --force-recreate


		echo "Updating file permissions in server..."
		docker_compose exec backend chown -R www-data:www-data /backend
		docker_compose exec backend find /backend -type f -exec chmod 644 {} \;
		docker_compose exec backend find /backend -type d -exec chmod 755 {} \;
		echo "File permissions updated in server"


	fi
	echo "Project rebuilt."


	# echo "Checking MySQL to be ready..."
	# while ! docker_compose exec database mysqladmin --user=${DB_USER} --password=${DB_ROOT_PASSWORD} --host "${LOCAL_IP}" ping --silent &> /dev/null ; do
	# 	echo "Waiting for database connection..."
	# 	sleep 3
	# done
	# echo "Site is ready!"


elif [[ $ACTION == down ]]; then


	if [[ $ENV_NAME != local-dev ]]; then

		read -ep "This action will stop the server. Are you sure you want to continue? (yes | no): " confirmation
		[[ $confirmation != "yes" ]] && exit || sleep 0
	
	fi


	echo "Closing the server..."
	docker_compose down
	echo "Server became down."


elif [[ $ACTION == update ]]; then


	read -ep "This action will stop the server for a moment. Are you sure you want to continue? (yes | no): " confirmation
	[[ $confirmation != "yes" ]] && exit || sleep 0



	echo "Updating the server..."
	docker_compose stop
	docker_compose rm -f
	docker_compose pull
	docker_compose up -d --build --force-recreate
	echo "Server up-to-date."


	echo "Updating file permissions in server..."
	docker_compose exec backend chown -R www-data:www-data /backend
	docker_compose exec backend find /backend -type f -exec chmod 644 {} \;
	docker_compose exec backend find /backend -type d -exec chmod 755 {} \;
	echo "File permissions updated in server"


	# echo "Checking MySQL to be ready..."
	# while ! docker_compose exec database mysqladmin --user=${DB_USER} --password=${DB_ROOT_PASSWORD} --host "${LOCAL_IP}" ping --silent &> /dev/null ; do
	# 	echo "Waiting for database connection..."
	# 	sleep 3
	# done
	# echo "Site is ready!"


elif [[ $ACTION == remove-logs ]]; then


	read -ep "This action will completely reset the logs. Are you sure you want to continue? (yes | no): " confirmation
	[[ $confirmation != "yes" ]] && exit || sleep 0


	echo "Removing the logs..."
	sh helpers/clean-logs.sh
	echo "Logs are removed."


	echo "Restarting the server..."
	docker_compose up -d --force-recreate
	echo "Server has been restarted."


elif [[ $ACTION == reset ]]; then


	read -ep "This action will completely reset the files/logs. And, will stop the server. Are you sure you want to continue? (yes | no): " confirmation
	[[ $confirmation != "yes" ]] && exit || sleep 0


	echo "Closing the server..."
	docker_compose down
	echo "Server became down."


	echo "Cleaning files..."
	sh helpers/clean-logs.sh
	sh helpers/clean-files.sh
	echo "All the project reset."


elif [[ $ACTION == prune ]]; then


	read -ep "This action will completely reset the Docker. And, will stop the server. Are you sure you want to continue? (yes | no): " confirmation
	[[ $confirmation != "yes" ]] && exit || sleep 0


	echo "Closing the server..."
	docker_compose down
	echo "Server became down."


	echo "Pruning the docker..."
	sh helpers/clean-docker.sh
	echo "Docker reset."


elif [[ $ACTION == reset-all ]]; then


	read -ep "This action will completely reset the Docker, files and logs. And, will stop the server. Are you sure you want to continue? (yes | no): " confirmation
	[[ $confirmation != "yes" ]] && exit || sleep 0


	echo "Closing the server..."
	docker_compose down
	echo "Server became down."


	echo "Resetting all..."
	sh helpers/clean-logs.sh
	sh helpers/clean-files.sh
	sh helpers/clean-docker.sh
	echo "All the project and Docker reset."


else


	if [[ -z $ACTION ]];then
		echo -e "${BLUE}Available actions:${RESET} install | pull | recreate | rebuild | down | update | remove-logs | reset | prune | reset-all"
	else
		echo -e "${BLUE}Skipped:${RESET} This action is not allowed on '$ENV_NAME' environment."
	fi

fi
